{{- if .Values.jobs.enroll.enabled }}
{{- $root := . }}
{{- $job := .Values.jobs.enroll }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "hlf-ca.fullname" . }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
{{ include "labels.standard" . | indent 4 }}
   job: enroll
spec:
  activeDeadlineSeconds: {{ $job.activeDeadlineSeconds }}
  backoffLimit: {{ $job.backoffLimit }}
  completions: {{ $job.completions }}
  parallelism: {{ $job.parallelism }}
  template:
    metadata:
      labels:
{{ include "labels.standard" . | indent 8 }}
        job: enroll
    spec:
      restartPolicy: {{ $job.restartPolicy }}
{{- if .Values.priorityClassName }}
      priorityClassName: "{{ .Values.priorityClassName }}"
{{- end }}
      containers:
        - name: enroll
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              echo ">\033[0;35m fabric-ca-client enroll -d -u http://$CA_ADMIN:$CA_PASSWORD@$SERVICE_DNS:7054\033[0m"
              fabric-ca-client enroll -d -u http://$CA_ADMIN:$CA_PASSWORD@$SERVICE_DNS:7054
          envFrom:
            - secretRef:
                name: {{ include "hlf-ca.fullname" . }}
            - configMapRef:
                name: {{ include "hlf-ca.fullname" . }}--db
            - configMapRef:
                name: {{ include "hlf-ca.fullname" . }}--ca  
          env:
          {{- range $key, $value := $job.env }}
            - name: {{ $key | upper | replace "." "_" }}
              value: {{ $value | quote }}
          {{- end }}
          resources:
{{ toYaml $job.resources | indent 12 }}
{{- end -}}